version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/com/epislab
    working_dir: /com/epislab
    command: python main.py
